#!/usr/bin/fish

function find_current_max
    set -l now 1
    set -l cur_max (tail -n+7 $argv[1] | cut -f1 -d. | wc -l)
    if test $cur_max -ge $now
        set now $cur_max
    end
    if test $now -lt 10
        echo "0$now"
    else
        echo $now
    end
end

set -l root (git rev-parse --show-toplevel)
set -l readme "$root/README.md"

set -l name $argv[1]
set -l num (find_current_max $readme)

if test $num -eq 1
    echo "" >> $readme
end

sed -i "\$i$num. [$name](src/$num-$name/main.go)" $readme
mkdir -p "$root/src/$num-$name"

